#!S:\swing_trading\swing_trader_ai\swingtrade-hybrid\hybrid_trader\Scripts\python.exe
# -*- coding: UTF-8 -*-
from __future__ import print_function, division, absolute_import

from numba.misc.numba_entry import main

if __name__ == "__main__":
    main()
